//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigurationKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigurationKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assignment2.ConfigurationKeys", typeof(ConfigurationKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEFAULT.
        /// </summary>
        internal static string DEFAULT_LOG {
            get {
                return ResourceManager.GetString("DEFAULT_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DURATION.
        /// </summary>
        internal static string DURATION {
            get {
                return ResourceManager.GetString("DURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIMITS.
        /// </summary>
        internal static string LIMITS {
            get {
                return ResourceManager.GetString("LIMITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCAL-COMMUNICATION.
        /// </summary>
        internal static string LOCAL_COMM {
            get {
                return ResourceManager.GetString("LOCAL_COMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAP.
        /// </summary>
        internal static string LOCAL_MAP {
            get {
                return ResourceManager.GetString("LOCAL_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGFILE.
        /// </summary>
        internal static string LOGFILE {
            get {
                return ResourceManager.GetString("LOGFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM-DOWNLOAD.
        /// </summary>
        internal static string MAX_DOWNLOAD {
            get {
                return ResourceManager.GetString("MAX_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM-PROCESSORS.
        /// </summary>
        internal static string MAX_PROC {
            get {
                return ResourceManager.GetString("MAX_PROC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM-PROCESSOR-FREQUENCIES.
        /// </summary>
        internal static string MAX_PROC_FREQ {
            get {
                return ResourceManager.GetString("MAX_PROC_FREQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM-RAM.
        /// </summary>
        internal static string MAX_RAM {
            get {
                return ResourceManager.GetString("MAX_RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM-TASKS.
        /// </summary>
        internal static string MAX_TASKS {
            get {
                return ResourceManager.GetString("MAX_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM-UPLOAD.
        /// </summary>
        internal static string MAX_UPLOAD {
            get {
                return ResourceManager.GetString("MAX_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM-DOWNLOAD.
        /// </summary>
        internal static string MIN_DOWNLOAD {
            get {
                return ResourceManager.GetString("MIN_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM-PROCESSORS.
        /// </summary>
        internal static string MIN_PROC {
            get {
                return ResourceManager.GetString("MIN_PROC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM-PROCESSOR-FREQUENCIES.
        /// </summary>
        internal static string MIN_PROC_FREQ {
            get {
                return ResourceManager.GetString("MIN_PROC_FREQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM-RAM.
        /// </summary>
        internal static string MIN_RAM {
            get {
                return ResourceManager.GetString("MIN_RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM-TASKS.
        /// </summary>
        internal static string MIN_TASKS {
            get {
                return ResourceManager.GetString("MIN_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM-UPLOAD.
        /// </summary>
        internal static string MIN_UPLOAD {
            get {
                return ResourceManager.GetString("MIN_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCESSORS.
        /// </summary>
        internal static string NUM_PROC {
            get {
                return ResourceManager.GetString("NUM_PROC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TASKS.
        /// </summary>
        internal static string NUM_TASKS {
            get {
                return ResourceManager.GetString("NUM_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C0.
        /// </summary>
        internal static string PROC_COEFF_0 {
            get {
                return ResourceManager.GetString("PROC_COEFF_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1.
        /// </summary>
        internal static string PROC_COEFF_1 {
            get {
                return ResourceManager.GetString("PROC_COEFF_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C2.
        /// </summary>
        internal static string PROC_COEFF_2 {
            get {
                return ResourceManager.GetString("PROC_COEFF_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWNLOAD.
        /// </summary>
        internal static string PROC_DOWNLOAD {
            get {
                return ResourceManager.GetString("PROC_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREQUENCY.
        /// </summary>
        internal static string PROC_FREQ {
            get {
                return ResourceManager.GetString("PROC_FREQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string PROC_ID {
            get {
                return ResourceManager.GetString("PROC_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        internal static string PROC_NAME_COEFF {
            get {
                return ResourceManager.GetString("PROC_NAME_COEFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM.
        /// </summary>
        internal static string PROC_RAM {
            get {
                return ResourceManager.GetString("PROC_RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE.
        /// </summary>
        internal static string PROC_TYPE {
            get {
                return ResourceManager.GetString("PROC_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCESSOR-TYPE.
        /// </summary>
        internal static string PROC_TYPE_COEFF {
            get {
                return ResourceManager.GetString("PROC_TYPE_COEFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCESSOR-TYPES.
        /// </summary>
        internal static string PROC_TYPES_COEFF {
            get {
                return ResourceManager.GetString("PROC_TYPES_COEFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPLOAD.
        /// </summary>
        internal static string PROC_UPLOAD {
            get {
                return ResourceManager.GetString("PROC_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCESSOR.
        /// </summary>
        internal static string PROCESSOR {
            get {
                return ResourceManager.GetString("PROCESSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCESSORS.
        /// </summary>
        internal static string PROCESSORS {
            get {
                return ResourceManager.GetString("PROCESSORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROGRAM.
        /// </summary>
        internal static string PROGRAM {
            get {
                return ResourceManager.GetString("PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFERENCE-FREQUENCY.
        /// </summary>
        internal static string REF_FREQ {
            get {
                return ResourceManager.GetString("REF_FREQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMOTE-COMMUNICATION.
        /// </summary>
        internal static string REMOTE_COMM {
            get {
                return ResourceManager.GetString("REMOTE_COMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAP.
        /// </summary>
        internal static string REMOTE_MAP {
            get {
                return ResourceManager.GetString("REMOTE_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWNLOAD.
        /// </summary>
        internal static string REQ_DOWNLOAD {
            get {
                return ResourceManager.GetString("REQ_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM.
        /// </summary>
        internal static string REQ_RAM {
            get {
                return ResourceManager.GetString("REQ_RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPLOAD.
        /// </summary>
        internal static string REQ_UPLOAD {
            get {
                return ResourceManager.GetString("REQ_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TASK.
        /// </summary>
        internal static string TASK {
            get {
                return ResourceManager.GetString("TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string TASK_ID {
            get {
                return ResourceManager.GetString("TASK_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUNTIME.
        /// </summary>
        internal static string TASK_RUNTIME {
            get {
                return ResourceManager.GetString("TASK_RUNTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TASKS.
        /// </summary>
        internal static string TASKS {
            get {
                return ResourceManager.GetString("TASKS", resourceCulture);
            }
        }
    }
}
