//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assignment2.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Download speed of processor is not sufficient for the allocated - Allocation {0}, Processor {1}.
        /// </summary>
        internal static string ALLOCATION_DOWNLOAD {
            get {
                return ResourceManager.GetString("ALLOCATION_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Missing ALLOCATION sub header.
        /// </summary>
        internal static string ALLOCATION_HEADER {
            get {
                return ResourceManager.GetString("ALLOCATION_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Task {0} has not been allocated to a processor.
        /// </summary>
        internal static string ALLOCATION_LESS_TASKS {
            get {
                return ResourceManager.GetString("ALLOCATION_LESS_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Wrong amount of processors in map.
        /// </summary>
        internal static string ALLOCATION_MAP_PROCESSORS {
            get {
                return ResourceManager.GetString("ALLOCATION_MAP_PROCESSORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Wrong number of Tasks in Map.
        /// </summary>
        internal static string ALLOCATION_MAP_TASKS {
            get {
                return ResourceManager.GetString("ALLOCATION_MAP_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Task {0} has been allocated to more than one processor in Allocation {1}.
        /// </summary>
        internal static string ALLOCATION_MORE_TASKS {
            get {
                return ResourceManager.GetString("ALLOCATION_MORE_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  RAM of processor is not sufficient for the allocated tasks - Allocation {0}, Processor {1}.
        /// </summary>
        internal static string ALLOCATION_RAM {
            get {
                return ResourceManager.GetString("ALLOCATION_RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Upload speed of processor is not sufficient for the allocated tasks - Allocation {0}, Processor {1}.
        /// </summary>
        internal static string ALLOCATION_UPLOAD {
            get {
                return ResourceManager.GetString("ALLOCATION_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Missing ALLOCATIONS header.
        /// </summary>
        internal static string ALLOCATIONS_HEADER {
            get {
                return ResourceManager.GetString("ALLOCATIONS_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Allocation ID is missing.
        /// </summary>
        internal static string ID_MISSING {
            get {
                return ResourceManager.GetString("ID_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Not all allocations have been validated.
        /// </summary>
        internal static string LESS_ALLOCATIONS {
            get {
                return ResourceManager.GetString("LESS_ALLOCATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Missing LIMITS data for validation.
        /// </summary>
        internal static string LIMITS {
            get {
                return ResourceManager.GetString("LIMITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Missing LIMITS header.
        /// </summary>
        internal static string LIMITS_HEADER {
            get {
                return ResourceManager.GetString("LIMITS_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Invalid Line or Keyword.
        /// </summary>
        internal static string LINE_ERROR {
            get {
                return ResourceManager.GetString("LINE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Expected LOCAL-COMMUNICATION data missing.
        /// </summary>
        internal static string LOCAL_DATA {
            get {
                return ResourceManager.GetString("LOCAL_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Missing LOCAL-COMMUCATION header.
        /// </summary>
        internal static string LOCAL_HEADER {
            get {
                return ResourceManager.GetString("LOCAL_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Missing LOGFILE data.
        /// </summary>
        internal static string LOGFILE {
            get {
                return ResourceManager.GetString("LOGFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Missing LOGFILE header.
        /// </summary>
        internal static string LOGFILE_HEADER {
            get {
                return ResourceManager.GetString("LOGFILE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  More allocations than expected.
        /// </summary>
        internal static string MORE_ALLOCATIONS {
            get {
                return ResourceManager.GetString("MORE_ALLOCATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Not a double.
        /// </summary>
        internal static string NOT_DOUBLE {
            get {
                return ResourceManager.GetString("NOT_DOUBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Not an integer.
        /// </summary>
        internal static string NOT_INTEGER {
            get {
                return ResourceManager.GetString("NOT_INTEGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Missing some processor info.
        /// </summary>
        internal static string PROCESSOR_DATA {
            get {
                return ResourceManager.GetString("PROCESSOR_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Missing Processor header.
        /// </summary>
        internal static string PROCESSOR_HEADER {
            get {
                return ResourceManager.GetString("PROCESSOR_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Missing PROCESSOR-TYPE header.
        /// </summary>
        internal static string PROCESSOR_TYPE_HEADER {
            get {
                return ResourceManager.GetString("PROCESSOR_TYPE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Missing PROCESSOR-TYPES header.
        /// </summary>
        internal static string PROCESSOR_TYPES_HEADER {
            get {
                return ResourceManager.GetString("PROCESSOR_TYPES_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Not all processors have been validated.
        /// </summary>
        internal static string PROCESSORS_DATA {
            get {
                return ResourceManager.GetString("PROCESSORS_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Missing Processors header.
        /// </summary>
        internal static string PROCESSORS_HEADER {
            get {
                return ResourceManager.GetString("PROCESSORS_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  More processors than expected.
        /// </summary>
        internal static string PROCESSORS_MORE {
            get {
                return ResourceManager.GetString("PROCESSORS_MORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Missing PROGRAM data for validation.
        /// </summary>
        internal static string PROGRAM {
            get {
                return ResourceManager.GetString("PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Missing PROGRAM header.
        /// </summary>
        internal static string PROGRAM_HEADER {
            get {
                return ResourceManager.GetString("PROGRAM_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Expected REMOTE-COMMUNICATION data missing.
        /// </summary>
        internal static string REMOTE_DATA {
            get {
                return ResourceManager.GetString("REMOTE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Missing REMOTE-COMMUNICATION header.
        /// </summary>
        internal static string REMOTE_HEADER {
            get {
                return ResourceManager.GetString("REMOTE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Missing TASK data for validation.
        /// </summary>
        internal static string TASK {
            get {
                return ResourceManager.GetString("TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Missing TASK Header.
        /// </summary>
        internal static string TASK_HEADER {
            get {
                return ResourceManager.GetString("TASK_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Missing TASKS Header.
        /// </summary>
        internal static string TASKS_HEADER {
            get {
                return ResourceManager.GetString("TASKS_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Not all Tasks have been validated.
        /// </summary>
        internal static string TASKS_LESS {
            get {
                return ResourceManager.GetString("TASKS_LESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  More tasks than expected.
        /// </summary>
        internal static string TASKS_MORE {
            get {
                return ResourceManager.GetString("TASKS_MORE", resourceCulture);
            }
        }
    }
}
