//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2.HeuristicAlgorithm {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HeuristicAlgorithm.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllocationsHeuristic", ReplyAction="http://tempuri.org/IService/GetAllocationsHeuristicResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFSLibrary.TimeoutFault), Action="http://tempuri.org/IService/GetAllocationsHeuristicTimeoutFaultFault", Name="TimeoutFault", Namespace="http://schemas.datacontract.org/2004/07/WCFSLibrary")]
        WCFSLibrary.AllocationData GetAllocationsHeuristic(int deadline, WCFSLibrary.ConfigData cd, int ID);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/GetAllocationsHeuristic", ReplyAction="http://tempuri.org/IService/GetAllocationsHeuristicResponse")]
        System.IAsyncResult BeginGetAllocationsHeuristic(int deadline, WCFSLibrary.ConfigData cd, int ID, System.AsyncCallback callback, object asyncState);
        
        WCFSLibrary.AllocationData EndGetAllocationsHeuristic(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Assignment2.HeuristicAlgorithm.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllocationsHeuristicCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllocationsHeuristicCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WCFSLibrary.AllocationData Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WCFSLibrary.AllocationData)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Assignment2.HeuristicAlgorithm.IService>, Assignment2.HeuristicAlgorithm.IService {
        
        private BeginOperationDelegate onBeginGetAllocationsHeuristicDelegate;
        
        private EndOperationDelegate onEndGetAllocationsHeuristicDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllocationsHeuristicCompletedDelegate;
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetAllocationsHeuristicCompletedEventArgs> GetAllocationsHeuristicCompleted;
        
        public WCFSLibrary.AllocationData GetAllocationsHeuristic(int deadline, WCFSLibrary.ConfigData cd, int ID) {
            return base.Channel.GetAllocationsHeuristic(deadline, cd, ID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAllocationsHeuristic(int deadline, WCFSLibrary.ConfigData cd, int ID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllocationsHeuristic(deadline, cd, ID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WCFSLibrary.AllocationData EndGetAllocationsHeuristic(System.IAsyncResult result) {
            return base.Channel.EndGetAllocationsHeuristic(result);
        }
        
        private System.IAsyncResult OnBeginGetAllocationsHeuristic(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int deadline = ((int)(inValues[0]));
            WCFSLibrary.ConfigData cd = ((WCFSLibrary.ConfigData)(inValues[1]));
            int ID = ((int)(inValues[2]));
            return this.BeginGetAllocationsHeuristic(deadline, cd, ID, callback, asyncState);
        }
        
        private object[] OnEndGetAllocationsHeuristic(System.IAsyncResult result) {
            WCFSLibrary.AllocationData retVal = this.EndGetAllocationsHeuristic(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllocationsHeuristicCompleted(object state) {
            if ((this.GetAllocationsHeuristicCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllocationsHeuristicCompleted(this, new GetAllocationsHeuristicCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllocationsHeuristicAsync(int deadline, WCFSLibrary.ConfigData cd, int ID) {
            this.GetAllocationsHeuristicAsync(deadline, cd, ID, null);
        }
        
        public void GetAllocationsHeuristicAsync(int deadline, WCFSLibrary.ConfigData cd, int ID, object userState) {
            if ((this.onBeginGetAllocationsHeuristicDelegate == null)) {
                this.onBeginGetAllocationsHeuristicDelegate = new BeginOperationDelegate(this.OnBeginGetAllocationsHeuristic);
            }
            if ((this.onEndGetAllocationsHeuristicDelegate == null)) {
                this.onEndGetAllocationsHeuristicDelegate = new EndOperationDelegate(this.OnEndGetAllocationsHeuristic);
            }
            if ((this.onGetAllocationsHeuristicCompletedDelegate == null)) {
                this.onGetAllocationsHeuristicCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllocationsHeuristicCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllocationsHeuristicDelegate, new object[] {
                        deadline,
                        cd,
                        ID}, this.onEndGetAllocationsHeuristicDelegate, this.onGetAllocationsHeuristicCompletedDelegate, userState);
        }
    }
}
